export const ErrorCode = {
  INVALID_NAME:     'INVALID_NAME',
  INVALID_ICON:     'INVALID_ICON',
  CODE_REQUIRED:    'CODE_REQUIRED',
  GROUP_NOT_FOUND:  'GROUP_NOT_FOUND',
  NOT_HOST:         'NOT_HOST',
  SELF_REMOVE:      'SELF_REMOVE',
  MEMBER_NOT_FOUND: 'MEMBER_NOT_FOUND',
  SERVER_ERROR:     'SERVER_ERROR',
}
